[package]
name = "ungrammar2json"
description = "Convert ungrammar files to JSON"
version = "1.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/matklad/ungrammar"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
edition = "2018"

[dependencies]
write-json = "0.1.1"
ungrammar = { path = "../", version = "1.1.0" }
